import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'
export const metadata = {
  title: 'Car Hub',
  description: 'Generated by discover the best cars',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative" >
        <Navbar />
        {children}</body>
        <Footer />
    </html>
  )
}
